//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathOrder.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PathOrderEntities1 : DbContext
    {
        public PathOrderEntities1()
            : base("name=PathOrderEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgenteAduanero> AgenteAduanero { get; set; }
        public virtual DbSet<Bulto> Bulto { get; set; }
        public virtual DbSet<Canal> Canal { get; set; }
        public virtual DbSet<DAM> DAM { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<FacturaMercaderia> FacturaMercaderia { get; set; }
        public virtual DbSet<Fecha> Fecha { get; set; }
        public virtual DbSet<Mercaderia> Mercaderia { get; set; }
        public virtual DbSet<OrdenDespacho> OrdenDespacho { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoDespacho> TipoDespacho { get; set; }
    }
}
