//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenDespacho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenDespacho()
        {
            this.Bulto = new HashSet<Bulto>();
            this.Factura = new HashSet<Factura>();
        }
    
        public int IdOrdenDespacho { get; set; }
        public int NumeroOrden { get; set; }
        public string Prioridad { get; set; }
        public string AWB_BL { get; set; }
        public string AWB_BLOrigen { get; set; }
        public string Origen { get; set; }
        public int CantidadSeries { get; set; }
        public int CantidadBultos { get; set; }
        public int IdTipoDespacho { get; set; }
        public int IdDAM { get; set; }
        public int IdProveedor { get; set; }
        public int IdCanal { get; set; }
        public int IdFecha { get; set; }
        public string Observacion { get; set; }
        public int IdAgenteAduanero { get; set; }
    
        public virtual AgenteAduanero AgenteAduanero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bulto> Bulto { get; set; }
        public virtual Canal Canal { get; set; }
        public virtual DAM DAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
        public virtual Fecha Fecha { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual TipoDespacho TipoDespacho { get; set; }
    }
}
