//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fecha
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fecha()
        {
            this.OrdenDespacho = new HashSet<OrdenDespacho>();
        }
    
        public int IdFecha { get; set; }
        public Nullable<System.DateTime> FechaEnumeracion { get; set; }
        public Nullable<System.DateTime> FechaRetiro { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public Nullable<System.DateTime> FechaLevante { get; set; }
        public Nullable<System.DateTime> FechaPrecosteo { get; set; }
        public Nullable<System.DateTime> KMMP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenDespacho> OrdenDespacho { get; set; }
    }
}
